package com.renault.entities;

import java.util.Arrays;
import java.util.Optional;

public enum Language {

    AB("Abkhazian"),
    AA("Afar"),
    AF("Afrikaans"),
    AK("Akan"),
    SQ("Albanian"),
    AM("Amharic"),
    AN("Aragonese"),
    HY("Armenian"),
    AS("Assamese"),
    AV("Avaric"),
    AE("Avestan"),
    AY("Aymara"),
    AZ("Azerbaijani"),
    BM("Bambara"),
    BA("Bashkir"),
    EU("Basque"),
    BE("Belarusian"),
    BN("Bengali"),
    BH("Bihari languages"),
    BI("Bislama"),
    BS("Bosnian"),
    BR("Breton"),
    BG("Bulgarian"),
    MY("Burmese"),
    CA("Catalan, Valencian"),
    CH("Chamorro"),
    CE("Chechen"),
    NY("Chichewa, Chewa, Nyanja"),
    ZH("Chinese"),
    CV("Chuvash"),
    KW("Cornish"),
    CO("Corsican"),
    CR("Cree"),
    HR("Croatian"),
    CS("Czech"),
    DA("Danish"),
    NL("Dutch, Flemish"),
    DZ("Dzongkha"),
    EN("English"),
    EO("Esperanto"),
    ET("Estonian"),
    EE("Ewe"),
    FO("Faroese"),
    FJ("Fijian"),
    FI("Finnish"),
    FR("French"),
    FF("Fulah"),
    GL("Galician"),
    KA("Georgian"),
    DE("German"),
    EL("Greek, Modern"),
    GN("Guarani"),
    GU("Gujarati"),
    HT("Haitian, Haitian Creole"),
    HZ("Herero"),
    HI("Hindi"),
    HO("Hiri Motu"),
    HU("Hungarian"),
    IA("Interlingua"),
    ID("Indonesian"),
    IE("Interlingue, Occidental"),
    GA("Irish"),
    IG("Igbo"),
    IK("Inupiaq"),
    IO("Ido"),
    IS("Icelandic"),
    IT("Italian"),
    IU("Inuktitut"),
    JA("Japanese"),
    JV("Javanese"),
    KL("Kalaallisut, Greenlandic"),
    KN("Kannada"),
    KR("Kanuri"),
    KS("Kashmiri"),
    KK("Kazakh"),
    KM("Central Khmer"),
    KI("Kikuyu, Gikuyu"),
    RW("Kinyarwanda"),
    KY("Kirghiz, Kyrgyz"),
    KV("Komi"),
    KG("Kongo"),
    KO("Korean"),
    KU("Kurdish"),
    KJ("Kuanyama, Kwanyama"),
    LA("Latin"),
    LB("Luxembourgish, Letzeburgesch"),
    LG("Ganda"),
    LI("Limburgan, Limburger, Limburgish"),
    LN("Lingala"),
    LO("Lao"),
    LT("Lithuanian"),
    LU("Luba-Katanga"),
    LV("Latvian"),
    GV("Manx"),
    MK("Macedonian"),
    MG("Malagasy"),
    MS("Malay"),
    ML("Malayalam"),
    MT("Maltese"),
    MI("Maori"),
    MR("Marathi"),
    MH("Marshallese"),
    MN("Mongolian"),
    NA("Nauru"),
    NV("Navajo, Navaho"),
    ND("North Ndebele"),
    NE("Nepali"),
    NG("Ndonga"),
    NB("Norwegian Bokmål"),
    NN("Norwegian Nynorsk"),
    NO("Norwegian"),
    II("Sichuan Yi, Nuosu"),
    NR("South Ndebele"),
    OC("Occitan"),
    OJ("Ojibwa"),
    CU("Church Slavic"),
    OM("Oromo"),
    OR("Oriya"),
    OS("Ossetian, Ossetic"),
    PA("Punjabi, Panjabi"),
    PI("Pali"),
    PL("Polish"),
    PT("Portuguese"),
    QU("Quechua"),
    RM("Romansh"),
    RN("Rundi"),
    RO("Romanian, Moldavian, Moldovan"),
    RU("Russian"),
    SA("Sanskrit"),
    SC("Sardinian"),
    SD("Sindhi"),
    SE("Northern Sami"),
    SM("Samoan"),
    SG("Sango"),
    SR("Serbian"),
    GD("Gaelic, Scottish Gaelic"),
    SN("Shona"),
    SI("Sinhala, Sinhalese"),
    SK("Slovak"),
    SL("Slovenian"),
    SO("Somali"),
    ST("Southern Sotho"),
    ES("Spanish, Castilian"),
    SU("Sundanese"),
    SW("Swahili"),
    SS("Swati"),
    SV("Swedish"),
    TA("Tamil"),
    TE("Telugu"),
    TG("Tajik"),
    TH("Thai"),
    TI("Tigrinya"),
    BO("Tibetan"),
    TK("Turkmen"),
    TL("Tagalog"),
    TN("Tswana"),
    TO("Tonga"),
    TR("Turkish"),
    TS("Tsonga"),
    TT("Tatar"),
    TW("Twi"),
    TY("Tahitian"),
    UG("Uighur, Uyghur"),
    UK("Ukrainian"),
    UZ("Uzbek"),
    VE("Venda"),
    VI("Vietnamese"),
    VO("Volapük"),
    WA("Walloon"),
    CY("Welsh"),
    WO("Wolof"),
    FY("Western Frisian"),
    XH("Xhosa"),
    YO("Yoruba"),
    ZA("Zhuang, Chuang"),
    ZU("Zulu"),
    ;

    private final String name;

    Language(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public static Optional<Language> fromName(String name) {
        return Arrays.stream(values()).filter(language -> language.name.equals(name)).findFirst();
    }

}
