@startuml

title
Synthesizrs - Entity Relation diagram
end title

hide circle
skinparam linetype ortho
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
skinparam note {
    BackgroundColor LightYellow
    ArrowColor Black
    BorderColor Black
}

entity "user" as user {
    *username : varchar
    --
    *password : varchar
}

entity "synthesizer" as synthesizer {
    *id : integer <<generated>>
    --
    *name : varchar
    *brand_id : integer <<foreign key>>
    *created_id : varchar <<foreign key>>
}

synthesizer "0..n" --> "1" user : createdBy

@enduml
